### ISSUE TITLE
Mac issue

### ISSUE THREAD

**Issue by den-vasyliev** [CHIP0K/DevOps-tools#2]
Could you please check this:

`➜  kbot git:(main) curl -sSL https://raw.githubusercontent.com/CHIP0K/DevOps-tools/main/git-hooks/gitleaks-setup.sh | bash
bash: line 3: /etc/environment: No such file or directory`

**Comment by CHIP0K** [comment]
Repaired path to the environment in MacOS [bb08e98](https://github.com/CHIP0K/DevOps-tools/commit/bb08e98e21061dbdb580e42cc127b020a696a3d8)
